[package]
name = "mk_lib_hardware"
version = "0.0.177"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_network = { version = "0.0.173", registry = "kellnr" }
mk_lib_logging = { version = "0.0.173", registry = "kellnr" }

futures = "0.3.31"
futures-util = "0.3.31"
huelib = "0.13.2"
LGremote = "0.2.1"
lsdp = "0.3.0"
mdns = "3.0.0"
mini-telnet = "0.1.8"
# onvif = { git = "https://github.com/lumeohq/onvif-rs" } # has request with default
rascam = { version = "0.0.2", optional = true }                     # breaks on mmal-sys compile - mmal-sys is for raspberry pi only
rppal = { version = "0.22.1", features = ["hal"], optional = true }
#rppal-dht11 = { version = "0.4.0", optional = true }
rups = { version = "0.6.1", features = ["async", "async-ssl"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serialport = "4.7.3"
smartcast = "0.1.1"
sonos_discovery = "0.0.2"
spl06-007 = { version = "0.3.3", optional = true }
#ssdp = { git = "https://github.com/ssnover/ssdp-rs", branch = "feature/local-impl-of-ip-feature" }
ssdp = { version = "0.7.0", registry = "kellnr" }
tokio = "1.49.0"
url = "2.5.8"
#weectrl = { git = "https://github.com/Hyperchaotic/weectrl" }
weectrl = { version = "2.0.2", registry = "kellnr" }
yeelib_rs = "0.1.1"

[features]
arduino = ["dep:spl06-007"]
#raspberry = ["dep:rascam", "dep:rppal", "dep:rppal-dht11"]
raspberry = ["dep:rascam", "dep:rppal"]

[dev-dependencies]
tokio-test = "*"
