apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-rabbit-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
