apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-openlibrary-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi
