apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-database-claim
  namespace: mkstack-mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs-csi-8k
