apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-transmission-downloads-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-csi
