apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mkstack-vosk-service
  name: mkstack-vosk-service
  namespace: mediakraken
spec:
  ports:
    - name: "2700"
      port: 2700
      targetPort: 2700
  selector:
    io.kompose.service: mkstack-vosk-service
