apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mkstack-nut-service
  name: mkstack-nut-service
  namespace: mediakraken
spec:
  ports:
    - name: "3493"
      port: 3493
      targetPort: 3493
  selector:
    io.kompose.service: mkstack-nut-service
