apiVersion: v1
kind: Service
metadata:
  name: mkstack-redis-service
  namespace: mediakraken
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
