apiVersion: v1
kind: Service
metadata:
  name: mkstack-webapp-service
  namespace: mediakraken
spec:
  type: NodePort
  ports:
    - name: "8900"
      port: 8900
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: mkstack-webapp-service
