apiVersion: v1
kind: Service
metadata:
  name: mkstack-elk-service
  namespace: mediakraken
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "5044"
      port: 5044
      targetPort: 5044
    - name: "5601"
      port: 5601
      targetPort: 5601
    - name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 39200
  selector:
    io.kompose.service: mkstack-elk-service
