apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mediakraken-vol-postgresql-backup
  name: mediakraken-vol-postgresql-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
