apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mkstack-wireguard
  name: mkstack-wireguard
spec:
  ports:
    - name: "51820"
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    io.kompose.service: mkstack-wireguard
