apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mkstack-nut
  name: mkstack-nut
spec:
  ports:
    - name: "3493"
      port: 3493
      targetPort: 3493
  selector:
    io.kompose.service: mkstack-nut
