apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mkstack-mumble
  name: mkstack-mumble
spec:
  ports:
    - name: "64738"
      port: 64738
      targetPort: 64738
    - name: 64738-udp
      port: 64738
      protocol: UDP
      targetPort: 64738
  selector:
    io.kompose.service: mkstack-mumble
