apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mkstack-vosk
  name: mkstack-vosk
spec:
  ports:
    - name: "2700"
      port: 2700
      targetPort: 2700
  selector:
    io.kompose.service: mkstack-vosk
