# https://rudimartinsen.com/2024/01/09/nfs-csi-driver-kubernetes/
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-8k
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.12
  share: /wdblack/sharenfs8k
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
