[package]
name = "mkiradio"
version = "0.0.1"
edition = "2024"


[dependencies]
mk_lib_common = { version = "0.0.224", registry = "kellnr" }
mk_lib_database = { version = "0.0.256", registry = "kellnr" }
mk_lib_file = { version = "0.0.234", registry = "kellnr" }
mk_lib_logging = { version = "0.0.225", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.228", registry = "kellnr" }

async-std = { version = "1.13.1", features = ["attributes"] }
chrono = { version = "0.4.45", features = ["serde"] }
fancy-regex = "0.18.0"
lazy_static = "1.5.0"
num-format = "0.4.4"
radiobrowser = "0.6.1"
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.23.2", features = ["serde", "v4", "v7"] }


[dev-dependencies]
tokio-test = "*"
