[package]
name = "mk_lib_share"
version = "0.0.246"
edition = "2024"
[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { version = "0.0.269", registry = "kellnr" }

pavao = { version = "0.2.16" }
tokio = { version = "1.23.2", features = ["fs", "process"] }
uuid = { version = "1.25.0", features = ["serde", "v4"] }

[dev-dependencies]
tokio-test = "*"
