---
- name : Setup k8s rabbitmq operator
  hosts: mkcontrol1
  tasks:
    - name: Install rabbitmq operator
      shell: kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml

    - name: copying file
      copy:
        src: ../config/rabbitmq.yml
        dest: ~/rabbitmq.yml

    - name: Setup cluster of rabbitmq
      shell: kubectl apply -f ~/rabbitmq.yml

    - name: Install rabbitmq monitor
      shell: kubectl apply --filename https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-servicemonitor.yml

    - name: Install rabbitmq operator monitor
      shell: kubectl apply --filename https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml

    - name: copying file
      copy:
        src: ../config/ingress_rabbit_http.yml
        dest: ~/ingress_rabbit_http.yml

    - name: Setup access user for rabbit ui
      shell: kubectl apply -f ~/ingress_rabbit_http.yml