[package]
name = "mkmulticast"
version = "0.0.1"
edition = "2024"


[dependencies]
# 0.31.0 breaks datalink
pnet = "0.30.0"
shiplift = { version = "0.7", default-features = false, features = [
    "unix-socket",
] }
tokio = { version = "1.52.3", features = ["macros", "net", "rt-multi-thread"] }

[dev-dependencies]
tokio-test = "*"
