[package]
name = "mkdownload"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { version = "0.0.113", registry = "kellnr" }
mk_lib_logging = { version = "0.0.82", registry = "kellnr" }
mk_lib_network = { version = "0.0.82", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.85", registry = "kellnr" }

chrono = { version = "0.4.43", features = ["serde"] }
csv = "1.4.0"
governor = "0.8.1"
reqwest = { version = "0.12.28", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.19.0", features = ["serde", "v4", "v7"] }
validator = { version = "0.20.0", features = ["derive"] }


[dev-dependencies]
tokio-test = "*"
