---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-http-monitoring-ingress-com
  namespace: monitoring
  annotations:
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/backend-protocol": "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster"   
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mkgrafana.mediakraken.media
      - mkprometheus.mediakraken.media
      secretName: letsencrypt-monitoring-priv
  rules:
  - host: mkgrafana.mediakraken.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
  - host: mkprometheus.mediakraken.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-prometheus
            port:
              number: 9090