loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2023-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  ingester:
    chunk_idle_period: 1h
    chunk_retain_period: 30s

deploymentMode: SingleBinary
# Disable microservices
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 20Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
