[package]
name = "mktestsharescanner"
version = "0.0.1"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_file = { path = "../../src/mk_lib_file" }
mk_lib_network = { path = "../../src/mk_lib_network" }

ipnet = "2.9.0"
ipnetwork = "0.20.0"
quickxml_to_serde = { version = "0.5.0", features = ["json_types"] }
reqwest = { version = "0.13.2", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
stdext = "0.3.3"
tokio = { version = "1.51.0", features = ["full"] }
walkdir = "2.5.0"

[dev-dependencies]
tokio-test = "*"
