apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-prometheus-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-csi
