apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-pgadmin-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-csi
