apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mkstack-wireguard-claim
  name: mkstack-wireguard-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-csi
