apiVersion: v1
kind: Namespace
metadata:
  name: dragonflydb
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: mkstack-dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: mkstack-dragonfly
  namespace: dragonflydb
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 4Gi
