# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
mkcontrol1 ansible_host=192.168.50.50  # ip=10.3.0.1 etcd_member_name=etcd1
mkcontrol2 ansible_host=192.168.50.51  # ip=10.3.0.2 etcd_member_name=etcd2
mkcontrol3 ansible_host=192.168.50.52  # ip=10.3.0.3 etcd_member_name=etcd3
mkworker1 ansible_host=192.168.50.60  # ip=10.3.0.4 etcd_member_name=etcd4
mkworker2 ansible_host=192.168.50.61  # ip=10.3.0.5 etcd_member_name=etcd5
mkworker3 ansible_host=192.168.50.62  # ip=10.3.0.6 etcd_member_name=etcd6

# ## configure a bastion host if your nodes are not directly reachable
# [bastion]
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube_control_plane]
mkcontrol1
mkcontrol2
mkcontrol3

[etcd]
mkcontrol1
mkcontrol2
mkcontrol3

[kube_node]
mkworker1
mkworker2
mkworker3

[kube_control_plane:vars]
node_labels={"workload_type":"control_plane"}

[kube_node:vars]
node_labels={"workload_type":"worker"}

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
