---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-monitoring-http-ingress-local
  namespace: monitoring
  annotations:
    # restrict to private network scopes
    # look at externalTrafficPolicy otherwise client ip is obfuscated "nginx.ingress.kubernetes.io/whitelist-source-range": "192.168.1.0/24"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/ssl-passthrough": "true"
    "nginx.ingress.kubernetes.io/backend-protocol": "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mkdevgrafana.mediakraken.media
      - mkdevprometheus.mediakraken.media
      secretName: letsencrypt-monitoring-priv
  rules:
  - host: mkdevgrafana.mediakraken.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
  - host: mkdevprometheus.mediakraken.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-prometheus
            port:
              number: 9090