---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gocd-http-ingress-local
  namespace: gocd
  annotations:
    # restrict to private network scopes
    # look at externalTrafficPolicy otherwise client ip is obfuscated "nginx.ingress.kubernetes.io/whitelist-source-range": "192.168.1.0/24"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/ssl-passthrough": "true"
    "nginx.ingress.kubernetes.io/backend-protocol": "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mkdevgocd.mediakraken.media
      secretName: letsencrypt-gocd-priv
  rules:
  - host: mkdevgocd.mediakraken.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gocdapp-server
            port:
              number: 8153