[package]
name = "mkmediascanner"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { version = "0.0.35", registry = "kellnr" }
mk_lib_database = { version = "0.0.66", registry = "kellnr" }
mk_lib_file = { version = "0.0.44", registry = "kellnr", features=["smb"] }
   # features=["nfs", "smb"] }
mk_lib_rabbitmq = { version = "0.0.39", registry = "kellnr" }

chrono = { version = "0.4.40", features = ["serde"] }
fancy-regex = "0.14.0"
lazy_static = "1.5.0"
num-format = "0.4.4"
reqwest = { version = "0.12.14", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rustls = "0.23.23"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.44.1", features = ["full"] }
uuid = { version = "1.16.0", features = ["serde", "v4", "v7"] }
walkdir = "2.5.0"

[dev-dependencies]
tokio-test = "*"
