[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { version = "0.0.213", registry = "kellnr" }
mk_lib_database = { version = "0.0.245", registry = "kellnr" }
mk_lib_logging = { version = "0.0.214", registry = "kellnr" }
mk_lib_metadata = { version = "0.0.225", registry = "kellnr" }
mk_lib_network = { version = "0.0.215", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.217", registry = "kellnr" }
mk_lib_share = { version = "0.0.222", registry = "kellnr" }

askama = "0.15.4"
askama_axum = "0.4.0"
async-trait = "0.1.89"
aws-config = "1.8.12"
aws-sdk-s3 = "1.119.0"
axum = { version = "0.8.8", features = ["form", "http2", "json", "multipart", "ws", "macros"] }
axum-client-ip = "1.3.1"
axum_csrf = "0.11.0"
axum-extra = { version = "0.12.5", features = ["routing"]}
axum-flash = { git = "https://github.com/aumetra/axum-flash", rev = "0832703" }
axum-messages = "0.8.0"
axum-prometheus = "0.10.0"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum_session = { version = "0.17.1", default-features = false, features = [
    "advanced",
    "key-store",
] }
axum_session_auth = { version = "0.17.0", default-features = false, features = [
    "advanced",
    "key-store",
] }
axum_session_sqlx = {version = "0.6.1", features = ["postgres", "tls-rustls"]}
bytesize = { version = "1.3.2", features = ["serde"] }  # 2.0.1 breaks my code
chrono = { version = "0.4.43", features = ["serde"] }
futures = "0.3.31"
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.19", features = ["client-legacy"] }
ipnetwork = "0.21.1"
lazy_static = "1.5.0"
libc = "0.2.180"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.6"
redis_pool = "0.10.0"
redis = { version = "1.0.3" }
reqwest = { version = "0.13.1", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = [
    "chrono",
    "ipnetwork",
    "json",
    "runtime-tokio",
    "postgres",
    "uuid",
] }
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tower = { version = "0.5.3", features = ["retry", "timeout", "util"] }
tower-http = { version = "0.6.8", features = ["fs", "set-header"] }
tower-sessions = "0.15.0"
transmission-rpc = "0.5.0"
uuid = { version = "1.20.0", features = ["serde", "v4", "v7"] }
urlencoding = "2.1.3"
validator = { version = "0.20.0", features = ["derive"] }


[dev-dependencies]
tokio-test = "*"
