[package]
name = "mk_lib_rabbitmq"
version = "0.0.237"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_logging = { version = "0.0.234", registry = "kellnr" }

amqprs = "2.1.5"
sys-info = "0.9.1"
tokio = "1.52.3"

[dev-dependencies]
tokio-test = "*"
