[package]
name = "mktmdbnetfetchbulk"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { version = "0.0.138", registry = "kellnr" }
mk_lib_compression = { version = "0.0.137", registry = "kellnr" }
mk_lib_database = { version = "0.0.170", registry = "kellnr" }
mk_lib_logging = { version = "0.0.139", registry = "kellnr" }
mk_lib_network = { version = "0.0.139", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.142", registry = "kellnr" }

chrono = { version = "0.4.43", features = ["serde"] }
reqwest = { version = "0.13.1", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.20.0", features = ["serde", "v4", "v7"] }

[dev-dependencies]
tokio-test = "*"
