[package]
name = "mktmdbnetfetchbulk"
version = "0.0.1"
edition = "2024"


[dependencies]
mk_lib_common = { version = "0.0.224", registry = "kellnr" }
mk_lib_compression = { version = "0.0.223", registry = "kellnr" }
mk_lib_database = { version = "0.0.256", registry = "kellnr" }
mk_lib_logging = { version = "0.0.225", registry = "kellnr" }
mk_lib_network = { version = "0.0.224", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.228", registry = "kellnr" }

chrono = { version = "0.4.45", features = ["serde"] }
sqlx = { version = "0.8.6", default-features = false, features = [
     "postgres",
     "runtime-tokio",
 ] }
reqwest = { version = "0.13.4", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.23.2", features = ["serde", "v4", "v7"] }

[dev-dependencies]
tokio-test = "*"
