[workspace]

members = [
    "mkcron",
    "mkdownload",
    "mkfanotify",
    "mkgamesdbnetfetchbulk",
    "mkglobalcache",
    "mkhardwarecontrol",
    "mkhardwarescanner",
    "mkinit",
    "mkinotify",
    "mkiradio",
    "mklibretrocorefetchupdate",
    "mkmediascanner",
    "mkmetadata",
    "mkmetadatamame",
    "mkmulticast",
    "mkmusicbrainz",
    "mkopenlibrarynetfetchbulk",
    "mkrabbitconsume",
    "mkschedulesdirectupdate",
    "mksharescanner",
    "mktmdbnetfetchbulk",
    "mktranscode",
    "mkwebaxum",
]
