[workspace]
resolver = "3"

members = [
    "mkcron",
    "mkdownload",
    "mkfanotify",
    "mkgamesdbnetfetchbulk",
    "mkglobalcache",
    "mkhardwarecontrol",
    "mkhardwarescanner",
    "mkinit",
    "mkinotify",
    "mkiradio",
    "mklibretrocorefetchupdate",
    "mkmediascanner",
    "mkmetadata",
    "mkmetadatamame",
    "mkmulticast",
    "mkmusicbrainz",
    "mkopenlibrarynetfetchbulk",
    "mkrabbitconsume",
    "mkschedulesdirectupdate",
    "mksharescanner",
    "mktmdbnetfetchbulk",
    "mktranscode",
    "mkwebaxum",
]

[profile.dev]
panic = 'unwind'
strip = "none"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true


[patch.crates-io]
hyper = { git = "https://github.com/hyperium/hyper", tag = "v0.10.16" }
