DEVICE_ITEM_TYPES = [
    "Amplifier",
    "Blu-ray Player",
    "Blu-ray Ultra HD Player",
    "Cable Box",
    "CD Player",
    "Chromecast",
    "Chromecast Ultra",
    "DAC",
    "DAT",
    "DVD Player",
    "DVR",
    "Game System",
    "HD-DVD Player",
    "HDHomeRun",
    "Internet Radio",
    "LaserDisc",
    "MiniDisc",
    "MUSE Laserdisc",
    "OTA Tuner",
    "PC",
    "Preamplifier",
    "Projector",
    "Radio",
    "Receiver",
    "Roku",
    "SACD",
    "Satellite Receiver",
    "Screen",
    "Tape Deck",
    "Television",
    "Tuner",
    "Turntable",
    "VCR - SVHS",
    "VCR - VHS",
    "VCR - Beta",
    "VCR - Super Beta",
    "Video Processor",
    "Video Switcher",
]