all:
  hosts:
    mkcontroldev1:
      ansible_host: 192.168.100.50
      ansible_user: metaman
    mkcontroldev2:
      ansible_host: 192.168.100.51
      ansible_user: metaman
    mkcontroldev3:
      ansible_host: 192.168.100.52
      ansible_user: metaman
    mkworker1:
      ansible_host: 192.168.100.60
      ansible_user: metaman
    mkworker2:
      ansible_host: 192.168.100.61
      ansible_user: metaman      
    mkworker3:
      ansible_host: 192.168.100.62
      ansible_user: metaman
  children:
    kube_control_plane:
      hosts:
        mkcontroldev1:
        mkcontroldev2:
        mkcontroldev3:
    kube_node:
      hosts:
        mkworkerdev1:
        mkworkerdev2:
        mkworkerdev3:
    etcd:
      hosts:
        mkcontroldev1:
        mkcontroldev2:
        mkcontroldev3: