# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
mkcontroldev1 ansible_host=192.168.1.50  # ip=10.3.0.1 etcd_member_name=etcd1
mkworkerdev1 ansible_host=192.168.1.60  # ip=10.3.0.4 etcd_member_name=etcd4
mkworkerdev2 ansible_host=192.168.1.61  # ip=10.3.0.4 etcd_member_name=etcd4
mkworkerdev3 ansible_host=192.168.1.62  # ip=10.3.0.4 etcd_member_name=etcd4

# ## configure a bastion host if your nodes are not directly reachable
# [bastion]
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube_control_plane]
mkcontroldev1

[etcd]
mkcontroldev1

[kube_node]
mkworkerdev1
mkworkerdev2
mkworkerdev3

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
