[kube_control_plane]
mkcontroldev1 ansible_host=192.168.1.50  # ip=10.3.0.1 etcd_member_name=etcd1

[etcd:children]
kube_control_plane

[kube_node]
mkworkerdev1 ansible_host=192.168.1.60  # ip=10.3.0.2
mkworkerdev2 ansible_host=192.168.1.61  # ip=10.3.0.3
mkworkerdev3 ansible_host=192.168.1.62  # ip=10.3.0.4

[kube_control_plane:vars]
node_labels={"workload_type":"control_plane"}

[kube_node:vars]
node_labels={"workload_type":"worker"}

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
