[package]
name = "theater_full"
version = "0.0.1"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_network = { version = "0.0.218", registry = "kellnr" }

fltk = { version = "1.5.22", features = ["fltk-bundled"] }
fltk-theme = "0.7.9"
tokio = { version = "1.49.0", features = ["rt"] }
