---
# https://artifacthub.io/packages/helm/gocd/gocd
- name : Setup gocd on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add gocd https://gocd.github.io/helm-chart

    - name: Install gocd
      shell: helm install gocdapp gocd/gocd \
        --create-namespace --namespace gocd \
        --set server.persistence.storageClass=local-path

    - name: copying file
      copy:
        src: ../config/ingress_gocd_http.yml
        dest: ~/ingress_gocd_http.yml

    - name: Setup cluster of ingress
      shell: kubectl apply -f ~/ingress_gocd_http.yml