---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
- name : Setup monitoring on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Install monitoring
      shell: helm install monitoring prometheus-community/kube-prometheus-stack \
        --create-namespace --namespace monitoring \
        --set global.storageClass=nfs-csi

    - name: copying file
      copy:
        src: ../config/ingress_monitoring_http.yml
        dest: ~/ingress_monitoring_http.yml

    - name: Setup cluster of ingress
      shell: kubectl apply -f ~/ingress_monitoring_http.yml

# kubectl get secret monitoring-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
# pasword = prom-operator
