---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
- name : Setup monitoring on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Install monitoring
      shell: helm install monitoring prometheus-community/kube-prometheus-stack \
        --set global.storageClass=nfs-csi

# pasword = prom-operator
