---
# https://artifacthub.io/packages/helm/bitnami/harbor
- name : Setup harbor on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Install harbor
      shell: helm install my-harbor bitnami/harbor --version 26.0.2 \
        --create-namespace --namespace harbor \
        --set global.defaultStorageClass=longhorn \
        --set externalURL=mkdevharbor.mediakraken.org \
        --set exposureType=ingress \
        --set persistence.enabled=true \
        --set persistence.persistentVolumeClaim.registry.storageClass=longhorn