---
# https://artifacthub.io/packages/helm/bitnami/jenkins
- name : Setup jenkins on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Install jenkins
      shell: helm install my-jenkins bitnami/jenkins --version 13.4.19 \
        --create-namespace --namespace jenkins \
        --set global.defaultStorageClass=longhorn \
        --set jenkinsUser=admin \
        --set jenkinsPassword=metaman

    - name: copying file
      copy:
        src: ../config/ingress_jenkins_http.yml
        dest: ~/ingress_jenkins_http.yml

    - name: Setup cluster of ingress
      shell: kubectl apply -f ~/ingress_jenkins_http.yml