# https://github.com/kellnr/helm
- name : Setup kellnr on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add kellnr https://kellnr.github.io/helm

    - name: Install kellnr
      shell: helm install kellnr kellnr/kellnr --set kellnr.origin.hostname="mkdevkellnr.mediakraken.media" \
        --create-namespace --namespace kellnr \
        --set pvc.enabled=true \
        --set pvc.storage=10Gi \
        --set pvc.storageClassName=longhorn \
        --set service.api.type=LoadBalancer \
        --set ingress.enabled=true \
        --set ingress.className=nginx \
        --set ingress.tls.secretName=letsencrypt-kellnr-priv \
        --set kellnr.proxy.enabled=true \
        --set kellnr.proxy.numThreads=50 \
        --set registry.auth_required=false
