---
# https://artifacthub.io/packages/helm/codecentric/mailhog
- name : Setup mailhog on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add codecentric https://codecentric.github.io/helm-charts

    - name: Install mailhog
      shell: helm install mailhog codecentric/mailhog \
        --create-namespace --namespace mailhog \
        --set ingress.enabled=true \
        --set ingress.hosts="{ host: mkdevmailhog.beaverbay.local, paths: [{ path: \"/\", pathType: Prefix }] }"

    # - name: copying file
    #   copy:
    #     src: ../config/ingress_mailhog_http.yml
    #     dest: ~/ingress_mailhog_http.yml

    # - name: Setup cluster of ingress
    #   shell: kubectl apply -f ~/ingress_mailhog_http.yml