---
# https://artifacthub.io/packages/helm/sonarqube/sonarqube-dce
# SonarQube is a self-managed, automatic code review tool that systematically helps you deliver clean code. 

# https://artifacthub.io/packages/helm/bitnami/sonarqube
# SonarQube(TM) is an open source quality management platform that analyzes and measures code's technical quality. It enables developers to detect code issues, vulnerabilities, and bugs in early stages.