---
# https://artifacthub.io/packages/helm/fermosit/taiga
- name : Setup taiga on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add fermosit https://harbor.fermosit.es/chartrepo/library

    - name: Install taiga
      shell: helm install my-taiga fermosit/taiga --version 0.0.11 \
        --create-namespace --namespace taiga \
