[package]
name = "mktestaxumauth"
version = "0.0.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
edition = "2024"

[dependencies]
axum = { version = "0.7.5" }
axum_session = { version = "0.14.0", default-features = false, features = [
    "advanced",
    "key-store",
] }
axum_session_auth = { version = "0.14.0", default-features = false, features = [
    "advanced",
    "key-store",
] }
axum_session_sqlx = {version = "0.1.0", features = ["sqlite"]}
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
tokio = { version = "1.41.0", features = ["full", "tracing"] }
async-trait = "0.1.80"
sqlx = { version = "0.8.2", features = [
    "macros",
    "migrate",
    "postgres",
    "sqlite",
    "_unstable-all-types",
    "tls-rustls",
    "runtime-tokio",
] }
anyhow = "1.0.86"
serde = "1.0.203"
