[package]
name = "mk_lib_compression"
version = "0.0.234"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_logging = { version = "0.0.236", registry = "kellnr" }

flate2 = "1.1.8"
serde_json = "1.0.150"
tar = "0.4.44"
tokio = { version = "1.52.3", features = ["rt"] }
zip = "4.5.0"

[dev-dependencies]
tokio-test = "*"
