# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
mkk8scontrol1 ansible_host=192.168.1.50  # ip=10.3.0.1 etcd_member_name=etcd1
mkk8scontrol2 ansible_host=192.168.1.51  # ip=10.3.0.2 etcd_member_name=etcd2
mkk8scontrol3 ansible_host=192.168.1.52  # ip=10.3.0.3 etcd_member_name=etcd3
mkk8sworker1 ansible_host=192.168.1.60  # ip=10.3.0.4 etcd_member_name=etcd4
mkk8sworker2 ansible_host=192.168.1.61  # ip=10.3.0.5 etcd_member_name=etcd5
mkk8sworker3 ansible_host=192.168.1.62  # ip=10.3.0.6 etcd_member_name=etcd6

# ## configure a bastion host if your nodes are not directly reachable
# [bastion]
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube_control_plane]
mkk8scontrol1
mkk8scontrol2
mkk8scontrol3

[etcd]
mkk8scontrol1
mkk8scontrol2
mkk8scontrol3

[kube_node]
mkk8sworker1
mkk8sworker2
mkk8sworker3

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
