[package]
name = "mk_lib_image"
version = "0.0.125"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_logging = { version = "0.0.127", registry = "kellnr" }

image = "0.25.9"
serde_json = "1.0.149"
wkhtmlapp = "1.0.2"

[dev-dependencies]
tokio-test = "*"
