[package]
name = "mk_lib_image"
version = "0.0.210"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_logging = { version = "0.0.211", registry = "kellnr" }

image = "0.25.10"
tokio = { version = "1.49.0", features = ["rt"] }
wkhtmlapp = "1.1.0"

[dev-dependencies]
tokio-test = "*"
