[package]
name = "mksharescanner"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { version = "0.0.240", registry = "kellnr" }
mk_lib_logging = { version = "0.0.209", registry = "kellnr" }
mk_lib_network = { version = "0.0.210", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.212", registry = "kellnr" }

chrono = { version = "0.4.43", features = ["serde"] }
ipnet = "2.11.0"
reqwest = { version = "0.13.2", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
sqlx = { version = "0.8.6", features = [
    "chrono",
    "ipnetwork",
    "json",
    "runtime-tokio",
    "postgres",
    "uuid",
] }
stdext = "0.3.3"
sys-info = "0.9.1"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.19.0", features = ["serde", "v4", "v7"] }
walkdir = "2.5.0"

[dev-dependencies]
tokio-test = "*"
