apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-hardwarescanner
  name: mkstack-hardwarescanner
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-hardwarescanner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-hardwarescanner
    spec:
      containers:
        - args:
            - sh
            - -c
            - /wait && /mkhardwarescanner
          env:
            - name: WAIT_HOSTS
              value: mkstack-database:5432, mkstack-rabbitmq:5672
            - name: WAIT_TIMEOUT
              value: "180"
          image: mediakraken/mkhardwarescanner:dev
          name: mkstack-hardwarescanner
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /mediakraken/phue
              name: mediakraken-vol-phue
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: mediakraken-vol-phue
          persistentVolumeClaim:
            claimName: mediakraken-vol-phue
