apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-wireguard
  name: mkstack-wireguard
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-wireguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-wireguard
    spec:
      containers:
        - env:
            - name: ALLOWEDIPS
              value: 0.0.0.0/0
            - name: INTERNAL_SUBNET
              value: 10.13.13.0
            - name: LOG_CONFS
              value: "true"
            - name: PEERDNS
              value: auto
            - name: PEERS
              value: "1"
            - name: PERSISTENTKEEPALIVE_PEERS
              value: all
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SERVERPORT
              value: "51820"
            - name: SERVERURL
              value: wireguard.domain.com
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/wireguard:latest
          name: mkstack-wireguard
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /config
              name: mediakraken-vol-wireguard
      restartPolicy: Always
      volumes:
        - name: mediakraken-vol-wireguard
          persistentVolumeClaim:
            claimName: mediakraken-vol-wireguard
