apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-wireshark
  name: mkstack-wireshark
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-wireshark-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-wireshark-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000 
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          # https://hub.docker.com/r/linuxserver/wireshark/tags
          image: linuxserver/wireshark:4.0.11
          name: mkstack-wireshark
          ports:
            - containerPort: 3001
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              name: mkstack-wireshark-claim
      restartPolicy: Always
      volumes:
        - name: mkstack-wireshark-claim
          persistentVolumeClaim:
            claimName: mkstack-wireshark-claim
