apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-prometheus
  name: mkstack-prometheus
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-prometheus-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-prometheus-service
    spec:
      containers:
        - image: prom/prometheus:v2.45.2
          name: mkstack-prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            # https://hub.docker.com/u/prom
            - mountPath: /etc/prometheus/prometheus.yml
              name: mkstack-prometheus-claim
      restartPolicy: Always
      volumes:
        - name: mkstack-prometheus-claim
          persistentVolumeClaim:
            claimName: mkstack-prometheus-claim
