apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-portainer
  name: mkstack-portainer
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-portainer-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-portainer-service
    spec:
      containers:
        - args:
            - -H
            - tcp://tasks.portaineragent:9001
            - --tlsskipverify
          image: portainer/portainer-ce:2.19.5-alpine
          name: mkstack-portainer
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: mkstack-portainer-claim
      restartPolicy: Always
      volumes:
        - name: mkstack-portainer-claim
          persistentVolumeClaim:
            claimName: mkstack-portainer-claim
