apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-certbot
  name: mkstack-certbot
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-certbot-service
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-certbot-service
    spec:
      containers:
        # https://github.com/certbot/certbot/releases
        - image: certbot/certbot:v2.11.0
          name: mkstack-certbot
      restartPolicy: Always
