apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-cron
  name: mkstack-cron
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-cron-service
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-cron-service
    spec:
      containers:
        - args:
            - sh
            - -c
            - /wait && /mkcron
          env:
            - name: WAIT_HOSTS
              value: mkstack-database:5432, mkstack-rabbitmq:5672
            - name: WAIT_TIMEOUT
              value: "180"
          image: mediakraken/mkcron:dev
          name: mkstack-cron
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
