apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-database
  name: mkstack-database
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-database-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-database-service
    spec:
      containers:
        - args:
            - postgres
            - -c
            - shared_preload_libraries=citus
            - -c
            - max_wal_size=16GB
            - -c
            - tcp_keepalives_idle=86400
            - -c
            - config_file=/usr/local/share/postgresql/postgresql.conf.sample
          env:
            - name: MAX_CONNECTIONS
              value: "125"
            - name: MAX_PARALLEL_WORKERS
              value: "8"
            - name: MAX_PARALLEL_WORKERS_PER_GATHER
              value: "2"
            - name: MAX_WAL_SENDERS
              value: "10"
            - name: MAX_WORKER_PROCESSES
              value: "8"
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/db-password
            - name: SHARED_BUFFERS
              value: 4096MB
            - name: WORK_MEM
              value: 64MB
          image: mediakraken/mkdatabase:dev
          name: mkstack-database
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /var/lib/postgresql/data
              name: mkstack-database-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: mkstack-database-claim
          persistentVolumeClaim:
            claimName: mkstack-database-claim
