apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    io.kompose.service: mkstack-portaineragent
  name: mkstack-portaineragent
  namespace: portainer
spec:
  selector:
    matchLabels:
      io.kompose.service: mkstack-portaineragent-service
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-portaineragent-service
    spec:
      containers:
        - env:
            - name: AGENT_CLUSTER_ADDR
              value: tasks.portaineragent
          image: portainer/agent:linux-amd64-2.19.5-alpine
          name: mkstack-portaineragent
      restartPolicy: Always
