apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-certs-claim
  namespace: mkstack-mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-csi
