apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkstack-comics-claim
  namespace: mediakraken
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
