apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-hardwarecontrol
  name: mkstack-hardwarecontrol
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-hardwarecontrol-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-hardwarecontrol-service
    spec:
      containers:
        - args:
            - sh
            - -c
            - /wait && /mkhardwarecontrol
          env:
            - name: WAIT_HOSTS
              value: pgcluster-with-metrics-rw.cnpg-system:5432, mkstack-rabbitmq-production.rabbitmq-system:5672
            - name: WAIT_TIMEOUT
              value: "180"
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: run-env-type
                  key: debug
          image: mediakraken/mkhardwarecontrol:dev
          imagePullPolicy: Always
          name: mkstack-hardwarecontrol
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
