apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-hardwarescanner
  name: mkstack-hardwarescanner
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-hardwarescanner-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-hardwarescanner-service
    spec:
      containers:
        - args:
            - sh
            - -c
            - /wait && /mkhardwarescanner
          env:
            - name: WAIT_HOSTS
              value: mkdatabase.stackgres:5432, mkstack-rabbitmq-service:5672
            - name: WAIT_TIMEOUT
              value: "180"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
          image: mediakraken/mkhardwarescanner:dev
          imagePullPolicy: Always
          name: mkstack-hardwarescanner
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
