apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-mediascanner
  name: mkstack-mediascanner
  namespace: mkstack-mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-mediascanner-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-mediascanner-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - args:
            - sh
            - -c
            - /wait && /mkmediascanner
          env:
            - name: WAIT_HOSTS
              value: mkstack-database-service:5432, mkstack-rabbitmq-service:5672
            - name: WAIT_TIMEOUT
              value: "180"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
          image: mediakraken/mkmediascanner:dev
          imagePullPolicy: Always
          name: mkstack-mediascanner
          volumeMounts:
            - mountPath: /mediakraken/metadata
              name: mkstack-metadata-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mkstack-metadata-claim
          persistentVolumeClaim:
            claimName: mkstack-metadata-claim
