# apiVersion: v1
# kind: Secret
# metadata:
#   name: "db-password"
# type: Opaque
# data:
#   db-password: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "secure-key"
type: Opaque
data:
  secure-key: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "csrf-key"
type: Opaque
data:
  csrf-key: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "nut-password"
type: Opaque
data:
  nut-password: {{ randAlphaNum 32 | b64enc | quote }}
