apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-tmdbnetfetchbulk
  name: mkstack-tmdbnetfetchbulk
  namespace: mkstack-mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-tmdbnetfetchbulk-service
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-tmdbnetfetchbulk-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - args:
            - sh
            - -c
            - /wait && /mktmdbnetfetchbulk
          env:
            - name: WAIT_HOSTS
              value: mkdatabase.stackgres:5432, mkstack-rabbitmq-service:5672
            - name: WAIT_TIMEOUT
              value: "180"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db-password
          image: mediakraken/mktmdbnetfetchbulk:dev
          imagePullPolicy: Always
          name: mkstack-tmdbnetfetchbulk
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
