apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mkstack-nut
  name: mkstack-nut
  namespace: mediakraken
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mkstack-nut-service
  template:
    metadata:
      labels:
        io.kompose.service: mkstack-nut-service
    spec:
      containers:
        - env:
            - name: nut-upsd-password
              valueFrom:
                secretKeyRef:
                  name: nut-password
                  key: mkstack-nut.txt
          image: mediakraken/mknut:dev
          imagePullPolicy: Always
          name: mkstack-nut
          ports:
            - containerPort: 3493
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
