all:
  hosts:
    mkcontrol1:
      ansible_host: 192.168.50.50
      ansible_user: metaman
    mkcontrol2:
      ansible_host: 192.168.50.51
      ansible_user: metaman
    mkcontrol3:
      ansible_host: 192.168.50.52
      ansible_user: metaman
    mkworker1:
      ansible_host: 192.168.50.60
      ansible_user: metaman
    mkworker2:
      ansible_host: 192.168.50.61
      ansible_user: metaman      
    mkworker3:
      ansible_host: 192.168.50.62
      ansible_user: metaman
  children:
    kube_control_plane:
      hosts:
        mkcontrol1:
        mkcontrol2:
        mkcontrol3:
    kube_node:
      hosts:
        mkworker1:
        mkworker2:
        mkworker3:
    etcd:
      hosts:
        mkcontrol1:
        mkcontrol2:
        mkcontrol3: