[package]
name = "mkinit"
version = "0.0.1"
edition = "2024"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { version = "0.0.128", registry = "kellnr" }
mk_lib_logging = { version = "0.0.97", registry = "kellnr" }

tokio = { version = "1.49.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
