---
- name : Setup local disks
  hosts: kube_node
  tasks:
    - name: Install lvm2 and iscsi
      shell: sudo apt install -y lvm2 open-iscsi && sudo systemctl enable iscsid && sudo systemctl start iscsid
      become: true
      become_method: sudo

    - name: Create vg
      shell: sudo vgcreate vgk8s1 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 && sudo vgcreate vgk8s2 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
      become: true
      become_method: sudo

    - name: Create lv
      shell: sudo lvcreate -l 100%VG -n vgk8s1lv vgk8s1 && sudo lvcreate -l 100%VG -n vgk8s2lv vgk8s2
      become: true
      become_method: sudo

    - name: Create file system
      shell: sudo mkfs.ext4 /dev/vgk8s1/vgk8s1lv && sudo mkfs.ext4 /dev/vgk8s2/vgk8s2lv
      become: true
      become_method: sudo

    - name: Update fstab
      shell: sudo echo "/dev/mapper/vgk8s1-vgk8s1lv /mnt/volume/disk1 ext4 defaults 0 0" >> /etc/fstab && sudo echo "/dev/mapper/vgk8s2-vgk8s2lv /mnt/volume/disk2 ext4 defaults 0 0" >> /etc/fstab && sudo systemctl daemon-reload
      become: true
      become_method: sudo

    - name: Create mount points
      shell: sudo mkdir -p /mnt/volume/disk1 && sudo mkdir -p /mnt/volume/disk2
      become: true
      become_method: sudo

    - name: Mount disks
      shell: sudo mount -a
      become: true
      become_method: sudo

    - name: Change rights
      shell: sudo chmod 777 /mnt/volume/disk1 && sudo chmod 777 /mnt/volume/disk2
      become: true
      become_method: sudo
