---
- name : Setup local disks
  hosts: kube_node
  tasks:
    - name: Install lvm2 and open-isci
      shell: sudo apt install -y lvm2 open-iscsi && sudo systemctl enable iscsid && sudo systemctl start iscsid
      become: true
      become_method: sudo

    - name: Create vg
      shell: sudo vgcreate vgk8s /dev/sdb && sudo vgcreate vglonghorn /dev/sdc
      become: true
      become_method: sudo

    - name: Create lv
      shell: sudo lvcreate -l 100%VG -n vgk8slv vgk8s && sudo lvcreate -l 100%VG -n vglonghornlv vglonghorn
      become: true
      become_method: sudo

    - name: Create file system
      shell: sudo mkfs.ext4 /dev/vgk8s/vgk8slv && sudo mkfs.ext4 /dev/vglonghorn/vglonghornlv
      become: true
      become_method: sudo

    - name: Update fstab
      shell: sudo echo -e "/dev/vgk8s/vgk8slv /mnt/volume/disk1 ext4 defaults 0 0\n/dev/vglonghorn/vglonghornlv /mnt/volume/disk2 ext4 defaults 0 0\n" >> /etc/fstab && sudo systemctl daemon-reload
      become: true
      become_method: sudo

    - name: Create mount point
      shell: sudo mkdir -p /mnt/volume/disk1 && sudo mkdir -p /mnt/volume/disk2
      become: true
      become_method: sudo

    - name: Mount disk
      shell: sudo mount -a
      become: true
      become_method: sudo

    - name: Change rights
      shell: sudo chmod 777 /mnt/volume/disk1
      become: true
      become_method: sudo

- name : Setup local disks
  hosts: mkcontrol1
  tasks:
    # - name: copying file
    #   copy:
    #     src: ../config/local_storage.yml
    #     dest: ~/local_storage.yml

    # - name: Setup local disk
    #   shell: kubectl apply -f ~/local_storage.yml

    - name: copying file
      copy:
        src: ../config/local_path_storage.yml
        dest: ~/local_path_storage.yml

    - name: Setup local disk
      shell: kubectl apply -f ~/local_path_storage.yml