---
- name : Setup longhorn ingress on cluster
  hosts: mkcontrol1
  tasks:
    - name: copying file
      copy:
        src: ../config/longhorn-ingress.yml
        dest: ~/longhorn-ingress.yml

    - name: Setup ingress for longhorn
      shell: kubectl apply -f ~/longhorn-ingress.yml
