---
- name : Setup longhorn on cluster
  hosts: mkcontrol1
  tasks:
    - name: Setup longhorn repo
      shell: helm repo add longhorn https://charts.longhorn.io
  
    - name: Install longhorn
      shell: helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system \
        --create-namespace --version 1.10.1

    # - name: Setup access user for longhorn ui
    #   shell: USER=metaman; PASSWORD=metaman; echo "${USER}:$(openssl passwd -stdin -apr1 <<< ${PASSWORD})" >> auth

    # - name: Setup secret for ui access
    #   shell: kubectl -n longhorn-system create secret generic basic-auth --from-file=auth

# kubectl -n longhorn-system get svc
