---
- name : Setup nfs capability
  hosts: kube_node
  tasks:
    - name: Setup NFS
      shell: sudo apt install -y nfs-common
      become: true
      become_method: sudo

- name : Setup nfs on cluster
  hosts: mkk8scontrol1
  tasks:
    - name: Setup NFS k8s driver
      shell: curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.9.0/deploy/install-driver.sh | bash -s v4.9.0 --

    - name: copying file
      copy:
        src: ../config/nfs-pvc.yml
        dest: ~/nfs-pvc.yml

    - name: Setup NFS shares
      shell: kubectl apply -f ~/nfs-pvc.yml
