apiVersion: v1
kind: Service
metadata:
  name: mkstack-wireguard-service
  namespace: mediakraken
spec:
  ports:
    - name: "51820"
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    io.kompose.service: mkstack-wireguard-service
