[package]
name = "mediakraken"
version = "0.0.1"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
dioxus = "0.7.3"
reqwest = { version = "0.13.2", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
dioxus-mobile = "0.6.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
dioxus-desktop = { version = "0.7.3", features = ["tokio_runtime"], default-features = false }

[dev-dependencies]
tokio-test = "*"
