[package]
name = "mediakraken"
version = "0.0.1"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
dioxus = "0.7.5"
reqwest = { version = "0.13.2", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
dioxus = { version = "0.7.5", features = ["mobile"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
dioxus = { version = "0.7.5", features = ["desktop"] }
