---
# https://artifacthub.io/packages/helm/gocd/gocd
- name : Setup gocd on cluster
  hosts: mkcontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add gocd https://gocd.github.io/helm-chart

    - name: Install gocd
      shell: helm install gocd_app gocd/gocd \
        --set server.persistence.storageClass=nfs-csi
