---
# https://artifacthub.io/packages/helm/fmjstudios/ntfy
# ntfy lets you send push notifications to your phone or desktop via scripts from any computer, using simple HTTP PUT or POST requests
# https://www.youtube.com/watch?v=poDIT2ruQ9M