---
- name : Setup operator on cluster
  hosts: mkk8scontroldev1
  tasks:
    - name: Install curl (if not already installed)
      package:
        name: curl
        state: present

    - name: Setup operator
      shell: curl -sL https://github.com/operator-framework/operator-controller/releases/download/v0.12.0/install.sh | bash -s v0.12.0
  