---
# https://artifacthub.io/packages/helm/rock8s/plane
# jira type tracking
- name : Setup plane on cluster
  hosts: mkk8scontroldev1
  tasks:
    - name: Add repo
      shell: helm repo add rock8s https://charts.rock8s.com

    - name: Install plane
      shell: helm install mk-plane rock8s/plane --version 1.0.22
