[package]
name = "mk_lib_hash"
version = "0.0.207"
edition = "2024"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
blake3 = "1.8.3"
crc32fast = "1.5.0"
#ed2k = { git = "https://github.com/runfalk/ed2k-rs" }
ed2k = { version = "0.3.0", registry = "kellnr" }
md-5 = "0.10.6"
sha1 = "0.10.6"
tokio = { version = "1.49.0", features = ["fs", "io-util"] }

[dev-dependencies]
tokio-test = "*"
