services:
  ray-worker:
    image: rayproject/ray:latest
    container_name: ray-worker
    network_mode: host
    restart: unless-stopped
    shm_size: "30gb"
    volumes:
      - /data:/data:rw
    environment:
      - RAY_ADDRESS=skynetgpu1:6379
    command:
      - "ray"
      - "start"
      - "--address=skynetgpu1:6379"
      - "--num-cpus=16"
      - "--num-gpus=0"
      - "--memory=120849018880"
      - "--block"